### ISSUE TITLE
Tapping received signal group photo shows black screen

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#4727]
Galaxy s5 stock ROM, signal 3.5.2. Friend on signal for android sends me photo. Preview is fine. Tapping the preview shows black screen. Saving the photo to gallery allows me to view photo.

**Comment by 2-4601** [comment]
Can**not** reproduce.
Signal 3.5.2. Nexus 4, stock 5.1.1. Huawei U8800, 4.0.4.
Tried both ways with quick capture shots, camera shots and attaching pictures.

**Comment by jeremymasters** [comment]
Photo taken by lgg4

**Comment by jeremymasters** [comment]
Also one sent from note 5 shows black

**Comment by jeremymasters** [comment]
Log from just trying to open that same file from earlier https://gist.github.com/4b305125273f02bcaa0f
Maybe it's just in groups because I just had someone send me a message and I was able to tap and view.

**Comment by riyapenn** [comment]
Not new to 3.5.2.  Other users (direct messages not group) have occasionally seen this when receiving very large pictures.

**Comment by mcginty** [comment]
sounds related to #4732

**Comment by mcginty** [comment]
potentially fixed by https://github.com/WhisperSystems/Signal-Android/pull/4737

**Comment by generalmanager** [comment]
@mcginty I'm on 3.6.1 and still having this issue with group-messages received a few days ago. Does your fix work retroactively or only for newly received messages?

I never had a problem with all-black thumbnails btw. Will send a log if I encounter the same problem with new messages.

**Comment by derpston** [comment]
Still happening for me and at least one of my contacts, 3.16.1.

When the enlarged photo display is black/empty, saving the photo produces a working image file. Re-sending it to the same group produces a message where the thumbnail can be tapped to view the enlarged photo.

**Comment by derpston** [comment]
Any ideas for debugging, anyone? @mcginty, perhaps? How can I help diagnose this for you folks?

**Comment by jeremymasters** [comment]
I haven't had this in a long time now.
