### ISSUE TITLE
Notifications reappear arbitrarily after dismissal

### ISSUE THREAD

**Issue by kvh** [WhisperSystems/Signal-Android#6218]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Notifications for unread messages reappear later when swiped away. No other app on my phone behaves this way and it is contrary to the purpose of a "notification": once dismissed it should not come back, I've been notified.

### Steps to reproduce
- Receive message
- Swipe away (dismiss) Android notification
- Wait (for indeterminate time, or another message to come in), notification reappears

**Actual result:** Original notification reappears
**Expected result:** Dismissed notification should not show up again

### Device info
**Android version:** 7.0
**Signal version:** 3.28.4

**Comment by 2-4601** [comment]
This seems to be a duplicate of #5751

**Comment by moxie0** [comment]
fixed in 3.32.0

**Comment by brianpittvps** [comment]
This is still an issue for me on Android 7.1.1 (not sure what the cutsie name is). It has nothing to do with new emails coming in, I would expect a new notification if a new email comes in. But if I swipe away new email notifications for Gmail, the notification shows up within seconds and I haven't gotten anything new.
