### ISSUE TITLE
Can't send photo/gif

### ISSUE THREAD

**Issue by benefaktorix** [WhisperSystems/Signal-Android#6316]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------
### Bug description
Attempt to send photo or video is unsuccessful, photos are not delivered, which leads to signal messages also not being delivered. To be able to send signal messages again, I must delete the photo I'm trying to send, delete the signal messages that were also not sent and only then I can send signal messages again, but still no photos/gifs. I've been experiencing this problem since today only (no app update today)

### Steps to reproduce
- attach photo/gif, press send
- after some time signal stops trying to send and says "message not delivered"
- delete photo/gif
- delete signal messages that were attempted to be sent afterwards
- now able to send signal messages but still not able to send photos/gifs

**Actual result:** Cannot send photos and gifs 
**Expected result:** Able to send cute cat pictures to friends and family

### Device info
**Device:** Blackberry Priv 
**Android version:** 6.0.1
**Signal version:** 3.30.4

### Link to debug log
https://gist.github.com/anonymous/c4cddcf79d721c92ab2cfdc8dddf2b32

**Comment by haffenloher** [comment]
That's a temporary server-side issue, see https://twitter.com/whispersystems/status/836651250842124288

**Comment by Trolldemorted** [comment]
Signal-Android should still be able to send messages if normal push messages *can* be delivered fine, though.

**Comment by benefaktorix** [comment]
Sorry, not using Twitter. i'm closing the issue

**Comment by moxie0** [comment]
S3 issues should be resolved

**Comment by Pratiwir** [comment]
https://debuglogs.org/1e90e8d84d1de70256b7a123d352e998a356804722829e120c46c474508d4520
I've got the same problem.
It took some time to upload the bug report but I managed at last. The file still doesn't send from pending.
Android 4.1.2 GT-I9082
Signal 4.34.8
